name: my_geek_hub
description: "an App to look for medias and keep the favorites"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/zeldabreathofthewild.jpg
    - assets/pokemonarceus.jpg
    - assets/leagueoflegends.jpg
    - assets/hearthstone.jpg
    - assets/valorant.jpg
    - assets/gta6.jpg
    - assets/fallguys.jpg
    - assets/overwatch.jpg
    - assets/worldofwarcraft.jpg
    - assets/minecraft.jpg
    - assets/demonslayer.jpg
    - assets/walle.jpeg
  uses-material-design: true
