name: my_geek_hub
description: "an App to look for medias and keep the favorites"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  assets:
    - assets/zeldabreathofthewild.jpg
    - assets/pokemonarceus.jpg
    - assets/hearthstone.jpg
    - assets/leagueoflegends.jpg
    - assets/worldofwarcraft.jpg
    - assets/valorant.jpg
    - assets/overwatch.jpg
    - assets/fallguys.jpg
    - assets/minecraft.jpg
    - assets/gta6.jpg
    - assets/attackontitan.jpg
    - assets/chainsawman.jpg
    - assets/demonslayer.jpg
    - assets/darlinginthefranxx.jpg
    - assets/yourlieinapril.jpg
    - assets/oshinoko.jpg
    - assets/frieren.jpg
    - assets/goldorak.jpg
    - assets/eightysix.jpg
    - assets/shimoneta.jpg
    - assets/walle.jpeg
    - assets/shrek.jpg
    - assets/mariobros.jpg
    - assets/yourname.jpg
    - assets/iwanttoeatyourpancreas.jpg
    - assets/weatheringwithyou.jpg
    - assets/spidermanintothespiderverse.jpg
    - assets/up.jpg
    - assets/suzume.jpeg
    - assets/spidermanbeyondthespiderverse.jpg
    - assets/logo_app.jpg

  uses-material-design: true
